### ISSUE TITLE
include a richer set of mongodb configurations

### ISSUE THREAD

**Issue by ear-dev** [RocketChat/helm-charts#1]
For example:  I would like to configure for tls and encryption on the persistent volumes.

**Comment by skadefro** [comment]
You have full access to configure mongodb, since they are referencing bitnami's helm chart for [mongodb](https://github.com/bitnami/charts/blob/master/bitnami/mongodb/values.yaml)
so to enable tls, in your values file add
```yaml
mongodb:
  enabled: true
  tls:
    enabled: true
    existingSecret: mongo-cert-secret
```
