### ISSUE TITLE
mongodb pre-upgrade job doesn't respect the mongodb chart's global.imageRegistry value

### ISSUE THREAD

**Issue by oatmonster** [RocketChat/helm-charts#116]
For example, if your values file contains something like:

```yaml
mongodb:
  global:
    imageRegistry: example.com
```

The pre-upgrade job will still try to create a job with image `docker.io/bitnami/mongodb:x.y.z` rather than `example.com/bitnami/mongodb:x.y.z`
