### ISSUE TITLE
smtp.existingSecret not/no longer working?

### ISSUE THREAD

**Issue by jenwirth** [RocketChat/helm-charts#129]
Hi,

Version: 6.7.6

We are using the following values:

```yaml
smtp:
    enabled: true
    existingSecret: es-mail
```

I can confirm the `MAIL_URL` env variable is set (`mail-url: smtp://xxxx@xxxx:pppppp@smtp.gmail.com:587 `

However email is not (or no longer) enabled (all the fields are empty in the workspace settings) and also not working.

tx.,
