### ISSUE TITLE
Incorrect URL in registered server

### ISSUE THREAD

**Issue by Falconx1000** [RocketChat/helm-charts#14]
Deployed Rocketchat with the helm chart including ingress and host value. When registering the server on cloud.rocket.chat the url for the self-hosted server only shows up as localhost:3000

**Comment by ewerton-silva00** [comment]
Hey, @Falconx1000 

It works with me. Example:

```yaml
## Host for the application
##
host: chat.mydomain.local

## Configure the ingress object to hook into existing infrastructure
### ref : http://kubernetes.io/docs/user-guide/ingress/
###

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  path: /
  tls:
    # - secretName: chart-example-tls
    #   hosts:
    #     - chat.mydomain.local

```
