### ISSUE TITLE
Wrong syntax in values.yaml

### ISSUE THREAD

**Issue by ariep** [RocketChat/helm-charts#16]
`values.yaml` now contains this:
```
mongodb:
  ## Enable or disable MongoDB dependency completely.
  enabled: true

  # auth.rootPassword:

  auth.username: rocketchat
  # auth.password:
  auth.database: rocketchat
```
I'm not sure if the syntax with the dot is supposed to be valid yaml, but in my experience it's not accepted by helm, which complains about the username not being set, unless I set it with my own
```
mongodb:
  auth:
    username: rocketchat
```
