### ISSUE TITLE
Missing prometheus port

### ISSUE THREAD

**Issue by danielwegener** [RocketChat/helm-charts#18]
RocketChat can expose prometheus metrics. This can be enabled via ui or env (OVERWRITE_SETTING_Prometheus_Enabled). 
In order to scrape rocketchat via prometheus operator (e.g. PodMonitor), it is required to declare the Pod metrics port, e.g.:

```
        ports:
        - name: http
          containerPort: 3000
        - name: metrics
          containerPort: 9458
          
```

A more elaborate implementation would put all these settings behind a value flag that would:

- set the environment variable OVERWRITE_SETTING_Prometheus_Enabled
- add the metrics port
- optionally add a prometheus operator PodMonitor
