### ISSUE TITLE
There is an error in your readme file

### ISSUE THREAD

**Issue by skadefro** [RocketChat/helm-charts#4]
The url for the chart is https://rocketchat.github.io/helm-charts/charts/
so in the readme it should say
```
$ helm repo add rocketchat https://rocketchat.github.io/helm-charts/charts/
```
also, it's good practice to publish a link to your values.yaml so we know what settings we have to work with

**Comment by skadefro** [comment]
oh, correction: the url is fine, but you need to move the index.yaml to the root folder
so 
/index.yaml
/charts/rocketchat-3.x.x.tgz

**Comment by skadefro** [comment]
And another correction, there is a **fatal** error in your Chart.yaml file
you are missing the condition on the dependency to mongodb, so it will install mongodb even when your dont want to!
it should be:
```
dependencies:
- name: mongodb
  repository: https://charts.bitnami.com/bitnami
  version: 7.x.x
  condition: mongodb.enabled
```
