### ISSUE TITLE
liveness probe is wrong

### ISSUE THREAD

**Issue by smulikHakipod** [RocketChat/helm-charts#49]
Hey,
It seems the liveness probes are wrong, because of this issue:
https://github.com/RocketChat/Rocket.Chat/issues/24795
It seems rocketchat is dead after a mongo disconnection, yet liveness probe in my case say the rocket chat is alive and well. 
We need to improve the liveness probe, or either fix upstream rocketchat? Any idea how do to that?

For now, I patched my local k8s rocketchat with that:
```
        livenessProbe:
          failureThreshold: 1
          exec:
            command:
              - /bin/sh
              - -c 
              - node -e "var net = require('net'); var s = new net.Socket(); s.connect(3000, '127.0.0.1', (e) => console.log('connected') && s.end()); s.end()" && node -e "var net = require('net'); var s = new net.Socket(); s.connect(27017, 'rocketchat-mongodb-headless', (e) => console.log('connected') && s.end()); s.end()"
          initialDelaySeconds: 60
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
```

which is probably far from ideal.

Thanks
