### ISSUE TITLE
warning: cannot overwrite table with non table for rocketchat.ingress.tls (map[])

### ISSUE THREAD

**Issue by stevek-pro** [RocketChat/helm-charts#66]
```
coalesce.go:220: warning: cannot overwrite table with non table for rocketchat.ingress.tls (map[])
coalesce.go:220: warning: cannot overwrite table with non table for rocketchat.ingress.tls (map[])
```

Then:

```
Rocket.Chat will be available at the URL:
- http://
```

What is this?

This is my ingress part:

```
ingress:
  enabled: true
  pathType: Prefix
  ingressClassName: "kong"
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/force-ssl-redirect: "true"
  path: /
  tls:
    - secretName: mydomain-rocketchat-tls
      hosts:
        - sub.mydomain.de
```
